//! # D-Bus interface proxy for: `com.github.digit1024.ttsstt.Service`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/com/github/digit1024/ttsstt' from service 'com.github.digit1024.ttsstt' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.github.digit1024.ttsstt.Service",
    default_service = "com.github.digit1024.ttsstt",
    default_path = "/com/github/digit1024/ttsstt"
)]
pub trait Service {
    /// Stop method
    fn stop(&self) -> zbus::Result<()>;

    /// Stt method
    fn stt(&self, language: &str, pause_duration: f64) -> zbus::Result<String>;

    /// SttType method
    fn stt_type(&self, language: &str, pause_duration: f64) -> zbus::Result<()>;

    /// Tts method
    fn tts(&self, text: &str, language: &str) -> zbus::Result<()>;

    /// StatusChanged signal
    #[zbus(signal)]
    fn status_changed(&self, status: &str) -> zbus::Result<()>;
}

