//! D-Bus client bindings for TTS/STT service
//!
//! This module contains auto-generated code from D-Bus introspection using zbus_xmlgen.
//! The code provides type-safe Rust bindings for the `com.github.digit1024.ttsstt` service.
//!
//! # Usage
//!
//! ```no_run
//! use cosmic_llm::dbus::generated::ServiceProxy;
//! use zbus::Connection;
//!
//! # async fn example() -> zbus::Result<()> {
//! let connection = Connection::session().await?;
//! let proxy = ServiceProxy::new(&connection).await?;
//! proxy.tts("Hello", "en").await?;
//! # Ok(())
//! # }
//! ```

pub mod generated;

// Always compile the module, but with different implementations based on feature flag
pub mod ttsstt;

// Re-export the client type (always available, with dummy implementation when feature disabled)
pub use ttsstt::DbusTtsSttClient;

// Re-export constants (always available, with dummy values when feature disabled)
pub use ttsstt::{SERVICE_INTERFACE, SERVICE_PATH};

// Note: The Service trait and ServiceProxy are generated by the #[proxy] macro
// Access them via: dbus::generated::Service and dbus::generated::ServiceProxy
